/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import Controller.BeverageController;
import Controller.BillDetailController;
import Controller.UserController;
import Model.BeverageModel;
import Model.BillDetailModel;
import Model.BillModel;
import Model.UserModel;
import Utils.BillUtils;
import java.awt.print.PrinterException;
import java.awt.print.PrinterJob;
import java.util.List;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author B1704721
 */
public class BillDetail extends javax.swing.JFrame {

    private BillModel billModel;
    private BillDetailController billDetailController;
    private UserController userController;
    private BeverageController beverageController;

    /**
     * Creates new form
     * @param billModel 
     */
    public BillDetail(BillModel billModel) {
        initComponents();
        setInterface();
        setBillDetail(billModel);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        labelTitle = new javax.swing.JLabel();
        labelBillId = new javax.swing.JLabel();
        labelBillIdValue = new javax.swing.JLabel();
        labelCreator = new javax.swing.JLabel();
        labelCreatorValue = new javax.swing.JLabel();
        labelCreateTime = new javax.swing.JLabel();
        labelCreateTimeValue = new javax.swing.JLabel();
        scrollPaneTable = new javax.swing.JScrollPane();
        tableBeverageList = new javax.swing.JTable();
        labelTotalAmount = new javax.swing.JLabel();
        labelTotalAmountValue = new javax.swing.JLabel();
        labelSubtotal = new javax.swing.JLabel();
        labelSubtotalValue = new javax.swing.JLabel();
        labelDiscount = new javax.swing.JLabel();
        labelDiscountValue = new javax.swing.JLabel();
        labelTotal = new javax.swing.JLabel();
        labelTotalValue = new javax.swing.JLabel();
        labelCash = new javax.swing.JLabel();
        labelCashValue = new javax.swing.JLabel();
        labelChange = new javax.swing.JLabel();
        labelChangeValue = new javax.swing.JLabel();
        buttonPrint = new javax.swing.JButton();
        buttonReturn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("KAT - Chi tiết hóa đơn");
        setResizable(false);

        labelTitle.setFont(new java.awt.Font("Times New Roman", 1, 30)); // NOI18N
        labelTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelTitle.setText("CHI TIẾT HÓA ĐƠN");

        labelBillId.setFont(new java.awt.Font("Times New Roman", 0, 22)); // NOI18N
        labelBillId.setText(" ID hóa đơn:");

        labelBillIdValue.setFont(new java.awt.Font("Times New Roman", 0, 22)); // NOI18N
        labelBillIdValue.setText("...");

        labelCreator.setFont(new java.awt.Font("Times New Roman", 0, 22)); // NOI18N
        labelCreator.setText(" Người tạo:");

        labelCreatorValue.setFont(new java.awt.Font("Times New Roman", 0, 22)); // NOI18N
        labelCreatorValue.setText("...");

        labelCreateTime.setFont(new java.awt.Font("Times New Roman", 0, 22)); // NOI18N
        labelCreateTime.setText(" Ngày tạo:");

        labelCreateTimeValue.setFont(new java.awt.Font("Times New Roman", 0, 22)); // NOI18N
        labelCreateTimeValue.setText("...");

        tableBeverageList.setFont(new java.awt.Font("Times New Roman", 0, 22)); // NOI18N
        tableBeverageList.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Thức uống", "Đơn giá", "Số lượng", "Thành tiền"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.Integer.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tableBeverageList.getTableHeader().setReorderingAllowed(false);
        scrollPaneTable.setViewportView(tableBeverageList);

        labelTotalAmount.setFont(new java.awt.Font("Times New Roman", 0, 22)); // NOI18N
        labelTotalAmount.setText(" Tổng số lượng:");

        labelTotalAmountValue.setFont(new java.awt.Font("Times New Roman", 0, 22)); // NOI18N
        labelTotalAmountValue.setText("...");

        labelSubtotal.setFont(new java.awt.Font("Times New Roman", 0, 22)); // NOI18N
        labelSubtotal.setText(" Tổng tiền:");

        labelSubtotalValue.setFont(new java.awt.Font("Times New Roman", 0, 22)); // NOI18N
        labelSubtotalValue.setText("...");

        labelDiscount.setFont(new java.awt.Font("Times New Roman", 0, 22)); // NOI18N
        labelDiscount.setText(" Khuyến mãi:");

        labelDiscountValue.setFont(new java.awt.Font("Times New Roman", 0, 22)); // NOI18N
        labelDiscountValue.setText("...");

        labelTotal.setFont(new java.awt.Font("Times New Roman", 0, 22)); // NOI18N
        labelTotal.setText(" Thành tiền:");

        labelTotalValue.setFont(new java.awt.Font("Times New Roman", 0, 22)); // NOI18N
        labelTotalValue.setText("...");

        labelCash.setFont(new java.awt.Font("Times New Roman", 0, 22)); // NOI18N
        labelCash.setText(" Tiền nhận:");

        labelCashValue.setFont(new java.awt.Font("Times New Roman", 0, 22)); // NOI18N
        labelCashValue.setText("...");

        labelChange.setFont(new java.awt.Font("Times New Roman", 0, 22)); // NOI18N
        labelChange.setText(" Tiền thối:");

        labelChangeValue.setFont(new java.awt.Font("Times New Roman", 0, 22)); // NOI18N
        labelChangeValue.setText("...");

        buttonPrint.setFont(new java.awt.Font("Times New Roman", 0, 22)); // NOI18N
        buttonPrint.setText("In");
        buttonPrint.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonPrintActionPerformed(evt);
            }
        });

        buttonReturn.setFont(new java.awt.Font("Times New Roman", 0, 22)); // NOI18N
        buttonReturn.setText("Trở về");
        buttonReturn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonReturnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(labelTitle, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(labelCreator)
                            .addComponent(labelCreateTime)
                            .addComponent(labelBillId))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(labelBillIdValue, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(labelCreatorValue, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(labelCreateTimeValue, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(buttonPrint)
                        .addGap(18, 18, 18)
                        .addComponent(buttonReturn)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(scrollPaneTable, javax.swing.GroupLayout.DEFAULT_SIZE, 540, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(labelChange)
                            .addComponent(labelCash)
                            .addComponent(labelTotal)
                            .addComponent(labelDiscount)
                            .addComponent(labelSubtotal)
                            .addComponent(labelTotalAmount))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(labelTotalAmountValue, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(labelSubtotalValue, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(labelDiscountValue, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(labelTotalValue, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(labelCashValue, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(labelChangeValue, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addGap(30, 30, 30))
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {labelBillId, labelCreateTime, labelCreator, labelSubtotal, labelTotalAmount});

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {buttonPrint, buttonReturn});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(labelTitle)
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(labelBillId)
                        .addGap(18, 18, 18)
                        .addComponent(labelCreator)
                        .addGap(18, 18, 18)
                        .addComponent(labelCreateTime))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(labelBillIdValue)
                        .addGap(18, 18, 18)
                        .addComponent(labelCreatorValue)
                        .addGap(18, 18, 18)
                        .addComponent(labelCreateTimeValue)))
                .addGap(18, 18, 18)
                .addComponent(scrollPaneTable, javax.swing.GroupLayout.DEFAULT_SIZE, 222, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(labelTotalAmount)
                        .addGap(18, 18, 18)
                        .addComponent(labelSubtotal)
                        .addGap(18, 18, 18)
                        .addComponent(labelDiscount)
                        .addGap(18, 18, 18)
                        .addComponent(labelTotal)
                        .addGap(18, 18, 18)
                        .addComponent(labelCash)
                        .addGap(18, 18, 18)
                        .addComponent(labelChange))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(labelTotalAmountValue)
                        .addGap(18, 18, 18)
                        .addComponent(labelSubtotalValue)
                        .addGap(18, 18, 18)
                        .addComponent(labelDiscountValue)
                        .addGap(18, 18, 18)
                        .addComponent(labelTotalValue)
                        .addGap(18, 18, 18)
                        .addComponent(labelCashValue)
                        .addGap(18, 18, 18)
                        .addComponent(labelChangeValue)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(buttonReturn)
                    .addComponent(buttonPrint))
                .addGap(30, 30, 30))
        );

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {labelBillIdValue, labelCashValue, labelChangeValue, labelCreateTimeValue, labelCreatorValue, labelDiscountValue, labelSubtotalValue, labelTotalAmountValue, labelTotalValue});

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
    
    private void setInterface() {
        // Set frame interface
        Settings.setFrameInterface(this);

        // Set table interface
        Settings.setTableInterface(tableBeverageList, scrollPaneTable);
    }

    private void setBillDetail(BillModel billModel) {
        // Init stuffs
        this.billModel = billModel;
        userController = new UserController();
        billDetailController = new BillDetailController();
        beverageController = new BeverageController();

        // Set bill detail
        List<BillDetailModel> billDetail = billDetailController.get(billModel.getId());
        labelBillIdValue.setText(String.valueOf(billModel.getId()));
        labelTotalAmountValue.setText(String.valueOf(billModel.getTotalAmount()));
        labelChangeValue.setText(String.valueOf(billModel.getChange()));
        labelCreateTimeValue.setText(String.valueOf(billModel.getCreateTime()));
        UserModel userModel = new UserModel();
        userModel = userController.get(billModel.getCreatorId());
        labelCreatorValue.setText(userModel.getFullName());
        labelDiscountValue.setText(String.valueOf(billModel.getDiscount() * 100) + "%");

        DefaultTableModel tableModel = (DefaultTableModel) tableBeverageList.getModel();
        for (BillDetailModel item : billDetail) {
            BeverageModel beverageModel = new BeverageModel();
            beverageModel = beverageController.get(item.getBeverageId());
            Object[] data = new Object[4];
            data[0] = beverageModel.getName();
            data[1] = beverageModel.getPrice();
            data[2] = item.getAmount();
            data[3] = beverageModel.getPrice() * item.getAmount();
            tableModel.addRow(data);
        }

        labelSubtotalValue.setText(String.valueOf(billModel.getSubtotal()));
        labelTotalValue.setText(String.valueOf(billModel.getTotal()));
        labelCashValue.setText(String.valueOf(billModel.getCash()));        
    }

    private void buttonPrintActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonPrintActionPerformed
        try {
            BillUtils utils = new BillUtils();
            utils.setBill(billModel, rootPane);
            PrinterJob pj = PrinterJob.getPrinterJob();
            pj.setPrintable(new BillUtils(billModel, rootPane), utils.getPageFormat(pj));
            pj.print();
        } catch (NullPointerException ex) {
            OptionPane.showMessageDialog("Lỗi", "Xảy ra lỗi khi in hóa đơn!");
        } catch (PrinterException ex) {
        }
    }//GEN-LAST:event_buttonPrintActionPerformed

    private void buttonReturnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonReturnActionPerformed
        this.dispose();
    }//GEN-LAST:event_buttonReturnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BillDetail.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BillDetail.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BillDetail.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BillDetail.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new BillDetail(new BillModel()).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonPrint;
    private javax.swing.JButton buttonReturn;
    private javax.swing.JLabel labelBillId;
    private javax.swing.JLabel labelBillIdValue;
    private javax.swing.JLabel labelCash;
    private javax.swing.JLabel labelCashValue;
    private javax.swing.JLabel labelChange;
    private javax.swing.JLabel labelChangeValue;
    private javax.swing.JLabel labelCreateTime;
    private javax.swing.JLabel labelCreateTimeValue;
    private javax.swing.JLabel labelCreator;
    private javax.swing.JLabel labelCreatorValue;
    private javax.swing.JLabel labelDiscount;
    private javax.swing.JLabel labelDiscountValue;
    private javax.swing.JLabel labelSubtotal;
    private javax.swing.JLabel labelSubtotalValue;
    private javax.swing.JLabel labelTitle;
    private javax.swing.JLabel labelTotal;
    private javax.swing.JLabel labelTotalAmount;
    private javax.swing.JLabel labelTotalAmountValue;
    private javax.swing.JLabel labelTotalValue;
    private javax.swing.JScrollPane scrollPaneTable;
    private javax.swing.JTable tableBeverageList;
    // End of variables declaration//GEN-END:variables
}
