/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

/**
 *
 * @author B1704721
 */
public class BillDetail extends javax.swing.JFrame {

    /**
     * Creates new form
     */
    public BillDetail() {
        initComponents();
        setInterface();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        labelTitle = new javax.swing.JLabel();
        buttonReturn = new javax.swing.JButton();
        labelAmountTotal = new javax.swing.JLabel();
        labelTotal = new javax.swing.JLabel();
        labelDiscount = new javax.swing.JLabel();
        labelMoneyToPay = new javax.swing.JLabel();
        labelReceivedMoney = new javax.swing.JLabel();
        labelChangeMoney = new javax.swing.JLabel();
        labelAmountTotalValue = new javax.swing.JLabel();
        labelTotalValue = new javax.swing.JLabel();
        labelDiscountValue = new javax.swing.JLabel();
        labelMoneyToPayValue = new javax.swing.JLabel();
        labelReceivedMoneyValue = new javax.swing.JLabel();
        labelChangeMoneyValue = new javax.swing.JLabel();
        scrollPaneTable = new javax.swing.JScrollPane();
        tableBeverageList = new javax.swing.JTable();
        labelCreatorId = new javax.swing.JLabel();
        labelBillIdValue = new javax.swing.JLabel();
        labelCreateTimeValue = new javax.swing.JLabel();
        labelBillId = new javax.swing.JLabel();
        labelCreatorIdValue = new javax.swing.JLabel();
        labelCreateTime = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("KAT - Chi tiết hóa đơn");
        setResizable(false);

        labelTitle.setFont(new java.awt.Font("Times New Roman", 1, 30)); // NOI18N
        labelTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelTitle.setText("CHI TIẾT HÓA ĐƠN");

        buttonReturn.setFont(new java.awt.Font("Times New Roman", 0, 22)); // NOI18N
        buttonReturn.setText("Trở về");
        buttonReturn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonReturnActionPerformed(evt);
            }
        });

        labelAmountTotal.setFont(new java.awt.Font("Times New Roman", 0, 22)); // NOI18N
        labelAmountTotal.setText("Tổng số lượng:");

        labelTotal.setFont(new java.awt.Font("Times New Roman", 0, 22)); // NOI18N
        labelTotal.setText("Tổng tiền hóa đơn:");

        labelDiscount.setFont(new java.awt.Font("Times New Roman", 0, 22)); // NOI18N
        labelDiscount.setText("Khuyến mãi:");

        labelMoneyToPay.setFont(new java.awt.Font("Times New Roman", 0, 22)); // NOI18N
        labelMoneyToPay.setText("Tiền phải trả:");

        labelReceivedMoney.setFont(new java.awt.Font("Times New Roman", 0, 22)); // NOI18N
        labelReceivedMoney.setText("Tiền nhận:");

        labelChangeMoney.setFont(new java.awt.Font("Times New Roman", 0, 22)); // NOI18N
        labelChangeMoney.setText("Tiền thối lại:");

        labelAmountTotalValue.setFont(new java.awt.Font("Times New Roman", 0, 22)); // NOI18N
        labelAmountTotalValue.setText("Tổng số thức uống");

        labelTotalValue.setFont(new java.awt.Font("Times New Roman", 0, 22)); // NOI18N
        labelTotalValue.setText("Tổng tiền hóa đơn");

        labelDiscountValue.setFont(new java.awt.Font("Times New Roman", 0, 22)); // NOI18N
        labelDiscountValue.setText("Số tiền được khuyến mãi");

        labelMoneyToPayValue.setFont(new java.awt.Font("Times New Roman", 0, 22)); // NOI18N
        labelMoneyToPayValue.setText("Số tiền khách hàng phải trả");

        labelReceivedMoneyValue.setFont(new java.awt.Font("Times New Roman", 0, 22)); // NOI18N
        labelReceivedMoneyValue.setText("Số tiền nhận từ khách hàng");

        labelChangeMoneyValue.setFont(new java.awt.Font("Times New Roman", 0, 22)); // NOI18N
        labelChangeMoneyValue.setText("Số tiền thối lại");

        tableBeverageList.setFont(new java.awt.Font("Times New Roman", 0, 22)); // NOI18N
        tableBeverageList.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"Name", "10000",  new Integer(4), null},
                {"Name", "20000",  new Integer(2), null}
            },
            new String [] {
                "Thức uống", "Đơn giá", "Số lượng", "Thành tiền"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.Integer.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tableBeverageList.getTableHeader().setReorderingAllowed(false);
        scrollPaneTable.setViewportView(tableBeverageList);

        labelCreatorId.setFont(new java.awt.Font("Times New Roman", 0, 22)); // NOI18N
        labelCreatorId.setText("Người tạo:");

        labelBillIdValue.setFont(new java.awt.Font("Times New Roman", 0, 22)); // NOI18N
        labelBillIdValue.setText("ID hóa đơn");

        labelCreateTimeValue.setFont(new java.awt.Font("Times New Roman", 0, 22)); // NOI18N
        labelCreateTimeValue.setText("Ngày tạo");

        labelBillId.setFont(new java.awt.Font("Times New Roman", 0, 22)); // NOI18N
        labelBillId.setText("ID hóa đơn:");

        labelCreatorIdValue.setFont(new java.awt.Font("Times New Roman", 0, 22)); // NOI18N
        labelCreatorIdValue.setText("ID người tạo");

        labelCreateTime.setFont(new java.awt.Font("Times New Roman", 0, 22)); // NOI18N
        labelCreateTime.setText("Ngày tạo:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(labelTitle, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(buttonReturn)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(scrollPaneTable, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(labelChangeMoney)
                                    .addComponent(labelReceivedMoney)
                                    .addComponent(labelMoneyToPay)
                                    .addComponent(labelDiscount)
                                    .addComponent(labelTotal)
                                    .addComponent(labelAmountTotal))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(labelChangeMoneyValue)
                                    .addComponent(labelReceivedMoneyValue)
                                    .addComponent(labelMoneyToPayValue)
                                    .addComponent(labelDiscountValue)
                                    .addComponent(labelTotalValue)
                                    .addComponent(labelAmountTotalValue))
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addGap(18, 18, 18))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(labelCreatorId)
                            .addComponent(labelCreateTime)
                            .addComponent(labelBillId))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(labelCreatorIdValue)
                            .addComponent(labelCreateTimeValue)
                            .addComponent(labelBillIdValue))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {labelAmountTotal, labelBillId, labelCreateTime, labelCreatorId, labelTotal});

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {labelAmountTotalValue, labelBillIdValue, labelChangeMoneyValue, labelCreateTimeValue, labelCreatorIdValue, labelDiscountValue, labelMoneyToPayValue, labelReceivedMoneyValue, labelTotalValue});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(labelTitle)
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(labelBillId)
                        .addGap(18, 18, 18)
                        .addComponent(labelCreatorId)
                        .addGap(18, 18, 18)
                        .addComponent(labelCreateTime))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(labelBillIdValue)
                        .addGap(18, 18, 18)
                        .addComponent(labelCreatorIdValue)
                        .addGap(18, 18, 18)
                        .addComponent(labelCreateTimeValue)))
                .addGap(18, 18, 18)
                .addComponent(scrollPaneTable, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(labelAmountTotal)
                        .addGap(18, 18, 18)
                        .addComponent(labelTotal)
                        .addGap(18, 18, 18)
                        .addComponent(labelDiscount)
                        .addGap(18, 18, 18)
                        .addComponent(labelMoneyToPay)
                        .addGap(18, 18, 18)
                        .addComponent(labelReceivedMoney)
                        .addGap(18, 18, 18)
                        .addComponent(labelChangeMoney))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(labelAmountTotalValue)
                        .addGap(18, 18, 18)
                        .addComponent(labelTotalValue)
                        .addGap(18, 18, 18)
                        .addComponent(labelDiscountValue)
                        .addGap(18, 18, 18)
                        .addComponent(labelMoneyToPayValue)
                        .addGap(18, 18, 18)
                        .addComponent(labelReceivedMoneyValue)
                        .addGap(18, 18, 18)
                        .addComponent(labelChangeMoneyValue)))
                .addGap(18, 18, 18)
                .addComponent(buttonReturn)
                .addGap(18, 18, 18))
        );

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {labelAmountTotalValue, labelBillIdValue, labelChangeMoneyValue, labelCreateTimeValue, labelCreatorIdValue, labelDiscountValue, labelMoneyToPayValue, labelReceivedMoneyValue, labelTotalValue});

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void setInterface() {
        // Set frame interface
        Settings.setFrameInterface(this);
        
        // Set table interface
        Settings.setTableInterface(tableBeverageList, scrollPaneTable);
    }
    
    private void buttonReturnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonReturnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_buttonReturnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BillDetail.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BillDetail.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BillDetail.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BillDetail.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new BillDetail().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonReturn;
    private javax.swing.JLabel labelAmountTotal;
    private javax.swing.JLabel labelAmountTotalValue;
    private javax.swing.JLabel labelBillId;
    private javax.swing.JLabel labelBillIdValue;
    private javax.swing.JLabel labelChangeMoney;
    private javax.swing.JLabel labelChangeMoneyValue;
    private javax.swing.JLabel labelCreateTime;
    private javax.swing.JLabel labelCreateTimeValue;
    private javax.swing.JLabel labelCreatorId;
    private javax.swing.JLabel labelCreatorIdValue;
    private javax.swing.JLabel labelDiscount;
    private javax.swing.JLabel labelDiscountValue;
    private javax.swing.JLabel labelMoneyToPay;
    private javax.swing.JLabel labelMoneyToPayValue;
    private javax.swing.JLabel labelReceivedMoney;
    private javax.swing.JLabel labelReceivedMoneyValue;
    private javax.swing.JLabel labelTitle;
    private javax.swing.JLabel labelTotal;
    private javax.swing.JLabel labelTotalValue;
    private javax.swing.JScrollPane scrollPaneTable;
    private javax.swing.JTable tableBeverageList;
    // End of variables declaration//GEN-END:variables
}
