/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import Controller.AdminController;
import Model.UserModel;
import javax.swing.ImageIcon;

/**
 *
 * @author B1704721
 */
public class HomeAdmin extends javax.swing.JFrame {

    private ImageIcon icon1 = new ImageIcon("src\\others\\icon-manage-user.png");
    private ImageIcon icon2 = new ImageIcon("src\\others\\icon-manage-bill.png");
    private ImageIcon icon3 = new ImageIcon("src\\others\\icon-manage-beverage.png");
    private ImageIcon icon4 = new ImageIcon("src\\others\\icon-sign-out.png");
    private AdminController adminController = new AdminController();
    private UserModel userModel = new UserModel();
    /**
     * Creates new form
     */
    public HomeAdmin() {
        initComponents();   
        buttonManageUser.setIcon(icon1);
        buttonCreateBill.setIcon(icon2);
        buttonManageBeverage.setIcon(icon3);
        buttonSignOut.setIcon(icon4);
        labelTitle.requestFocus();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        labelTitle = new javax.swing.JLabel();
        buttonManageUser = new javax.swing.JButton();
        buttonCreateBill = new javax.swing.JButton();
        buttonManageBeverage = new javax.swing.JButton();
        buttonSignOut = new javax.swing.JButton();
        menuBar = new javax.swing.JMenuBar();
        menuManageBill = new javax.swing.JMenu();
        menuItemCreateBill = new javax.swing.JMenuItem();
        menuItemViewBillHistory = new javax.swing.JMenuItem();
        menuManageBeverage = new javax.swing.JMenu();
        menuSignOut = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("KAT - Trang chủ");
        setResizable(false);

        labelTitle.setFont(new java.awt.Font("Times New Roman", 1, 30)); // NOI18N
        labelTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelTitle.setText("HỆ THỐNG QUẢN LÝ QUÁN NƯỚC KISS A TEN");

        buttonManageUser.setFont(new java.awt.Font("Times New Roman", 0, 22)); // NOI18N
        buttonManageUser.setToolTipText("Quản lý người dùng");
        buttonManageUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonManageUserActionPerformed(evt);
            }
        });

        buttonCreateBill.setFont(new java.awt.Font("Times New Roman", 0, 22)); // NOI18N
        buttonCreateBill.setToolTipText("Tạo hóa đơn");
        buttonCreateBill.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonCreateBillActionPerformed(evt);
            }
        });

        buttonManageBeverage.setFont(new java.awt.Font("Times New Roman", 0, 22)); // NOI18N
        buttonManageBeverage.setToolTipText("Quản lý thức uống");
        buttonManageBeverage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonManageBeverageActionPerformed(evt);
            }
        });

        buttonSignOut.setFont(new java.awt.Font("Times New Roman", 0, 22)); // NOI18N
        buttonSignOut.setToolTipText("Đăng xuất");
        buttonSignOut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonSignOutActionPerformed(evt);
            }
        });

        menuBar.setToolTipText("");
        menuBar.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N

        menuManageBill.setText("Quản lý hóa đơn   ");
        menuManageBill.setFont(new java.awt.Font("Times New Roman", 0, 22)); // NOI18N

        menuItemCreateBill.setFont(new java.awt.Font("Times New Roman", 0, 22)); // NOI18N
        menuItemCreateBill.setText("Tạo hóa đơn");
        menuItemCreateBill.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemCreateBillActionPerformed(evt);
            }
        });
        menuManageBill.add(menuItemCreateBill);

        menuItemViewBillHistory.setFont(new java.awt.Font("Times New Roman", 0, 22)); // NOI18N
        menuItemViewBillHistory.setText("Xem lịch sử hóa đơn");
        menuItemViewBillHistory.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemViewBillHistoryActionPerformed(evt);
            }
        });
        menuManageBill.add(menuItemViewBillHistory);

        menuBar.add(menuManageBill);

        menuManageBeverage.setText("Quản lý thức uống   ");
        menuManageBeverage.setFont(new java.awt.Font("Times New Roman", 0, 22)); // NOI18N
        menuManageBeverage.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menuManageBeverageMouseClicked(evt);
            }
        });
        menuBar.add(menuManageBeverage);

        menuSignOut.setText("Đăng xuất   ");
        menuSignOut.setFont(new java.awt.Font("Times New Roman", 0, 22)); // NOI18N
        menuSignOut.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menuSignOutMouseClicked(evt);
            }
        });
        menuBar.add(menuSignOut);

        setJMenuBar(menuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(labelTitle, javax.swing.GroupLayout.DEFAULT_SIZE, 747, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(buttonManageBeverage, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(buttonManageUser, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(buttonCreateBill, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE)
                    .addComponent(buttonSignOut, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {buttonCreateBill, buttonManageBeverage, buttonManageUser, buttonSignOut});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(labelTitle)
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(buttonManageUser, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buttonCreateBill, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(buttonSignOut, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(buttonManageBeverage, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE))
                .addGap(35, 35, 35))
        );

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {buttonCreateBill, buttonManageBeverage, buttonManageUser, buttonSignOut});

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Lay username o day
     * @param model 
     */
    public void setUser(UserModel model){
        userModel = adminController.get(model);
    }
    
    private void buttonCreateBillActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonCreateBillActionPerformed
        CreateBill form = new CreateBill();
        form.setVisible(true);
    }//GEN-LAST:event_buttonCreateBillActionPerformed

    private void buttonManageBeverageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonManageBeverageActionPerformed
        ManageBeverage form = new ManageBeverage();
        form.setVisible(true);
    }//GEN-LAST:event_buttonManageBeverageActionPerformed

    private void buttonSignOutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonSignOutActionPerformed
        this.dispose();
        this.getParent().setVisible(true);
    }//GEN-LAST:event_buttonSignOutActionPerformed

    private void menuItemCreateBillActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemCreateBillActionPerformed
        CreateBill form = new CreateBill();
        form.setVisible(true);
    }//GEN-LAST:event_menuItemCreateBillActionPerformed

    private void menuItemViewBillHistoryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemViewBillHistoryActionPerformed
        ViewBillHistory form = new ViewBillHistory();
        form.setVisible(true);
    }//GEN-LAST:event_menuItemViewBillHistoryActionPerformed

    private void menuManageBeverageMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuManageBeverageMouseClicked
        ManageBeverage form = new ManageBeverage();
        form.setVisible(true);
    }//GEN-LAST:event_menuManageBeverageMouseClicked

    private void menuSignOutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuSignOutMouseClicked
        this.dispose();
        this.getParent().setVisible(true);
    }//GEN-LAST:event_menuSignOutMouseClicked

    private void buttonManageUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonManageUserActionPerformed
        ManageUser form = new ManageUser();
        form.setVisible(true);
    }//GEN-LAST:event_buttonManageUserActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(HomeAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(HomeAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(HomeAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(HomeAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new HomeAdmin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonCreateBill;
    private javax.swing.JButton buttonManageBeverage;
    private javax.swing.JButton buttonManageUser;
    private javax.swing.JButton buttonSignOut;
    private javax.swing.JLabel labelTitle;
    private javax.swing.JMenuBar menuBar;
    private javax.swing.JMenuItem menuItemCreateBill;
    private javax.swing.JMenuItem menuItemViewBillHistory;
    private javax.swing.JMenu menuManageBeverage;
    private javax.swing.JMenu menuManageBill;
    private javax.swing.JMenu menuSignOut;
    // End of variables declaration//GEN-END:variables
}
